@startuml
' !theme cerulean vibrant blueprint mars
!include ./puml-theme-boby.puml
autonumber

title OAuth2 Client Credentials Flow with Resource Server and JWT Token

actor Client
Client -> ResourceServer: Request protected resource
ResourceServer --> Client: Unauthorized

Client -> OAuthServer: Request access token
OAuthServer --> Client: Access token (JWT)

Client -> ResourceServer: Request protected resource with token

ResourceServer --> ResourceServer: Check key ID of the token exist in the cache

alt Key ID is not in the cache
    ResourceServer -> OAuthServer: Get public key from JWKS url (Typically called ONCE ONLY unless new key ID is generated)
    OAuthServer --> ResourceServer: List of public keys for all key IDs

    ResourceServer --> ResourceServer: Cache new public keys agaist new Key IDs
end

ResourceServer --> ResourceServer: Get public key from the cache by Key ID

ResourceServer --> ResourceServer: Validate token using the public key
ResourceServer --> Client: Protected resource

@enduml
